# Generated by Django 3.2.8 on 2021-11-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('enunciado', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Incorrecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_equivocada', models.CharField(blank=True, default='', max_length=50)),
                ('id_pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.plantilla')),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_estudiantes',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.grupos')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Correcta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=50)),
                ('respuesta', models.CharField(max_length=50)),
                ('id_pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.plantilla')),
            ],
        ),
        migrations.CreateModel(
            name='Banco_preguntas',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.curso')),
            ],
        ),
    ]
