# Generated by Django 3.2.8 on 2021-10-25 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco_preguntas',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profe',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('id_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.banco_preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_estudiantes',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.grupos')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='profe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.profe'),
        ),
        migrations.AddField(
            model_name='banco_preguntas',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.curso'),
        ),
    ]
