# Generated by Django 3.2.8 on 2021-11-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco_preguntas',
            name='dni',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
