# Generated by Django 3.2.8 on 2021-11-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupos',
            name='dni',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
