# Generated by Django 3.2.8 on 2021-10-27 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pregunta',
            new_name='Plantilla',
        ),
        migrations.CreateModel(
            name='Incorrecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_equivocada', models.CharField(max_length=50)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.plantilla')),
            ],
        ),
        migrations.CreateModel(
            name='Correcta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=50)),
                ('respuesta', models.CharField(max_length=50)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.plantilla')),
            ],
        ),
    ]
