# Generated by Django 3.2.8 on 2021-11-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='id_banco',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.banco_preguntas'),
        ),
    ]
