# Generated by Django 3.2.8 on 2021-11-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0002_alter_banco_preguntas_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco_preguntas',
            name='dni',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grupo_estudiantes',
            name='dni',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
