# Generated by Django 3.2.8 on 2021-11-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0003_auto_20211116_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.AlterField(
            model_name='curso',
            name='dni',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='dni',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
