# Generated by Django 3.2.8 on 2021-10-31 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0003_plantilla_enunciado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='profe',
        ),
        migrations.DeleteModel(
            name='Profe',
        ),
    ]
