# Generated by Django 3.2.8 on 2021-11-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0004_auto_20211031_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='incorrecta',
            name='respuesta_equivocada',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
