# Generated by Django 3.2.8 on 2021-11-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0005_auto_20211106_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correcta',
            name='id_pregunta',
        ),
        migrations.RemoveField(
            model_name='incorrecta',
            name='id_pregunta',
        ),
        migrations.RemoveField(
            model_name='plantilla',
            name='id_banco',
        ),
    ]
