# Generated by Django 3.2.8 on 2021-11-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0006_auto_20211106_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correcta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='incorrecta',
            name='id',
        ),
        migrations.AddField(
            model_name='correcta',
            name='id_pregunta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.plantilla'),
        ),
        migrations.AddField(
            model_name='grupo_estudiantes',
            name='nombre_estudiante',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incorrecta',
            name='idIncorrecta',
            field=models.AutoField(default='st', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incorrecta',
            name='id_pregunta',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.plantilla'),
        ),
        migrations.AlterField(
            model_name='correcta',
            name='respuesta',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grupo_estudiantes',
            name='dni',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grupo_estudiantes',
            name='id_estudiante',
            field=models.CharField(max_length=10),
        ),
    ]
